# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.CharField(db_column='id', max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', default='NULL', max_length=100)),
                ('year', models.IntegerField(db_column='year', default=0, max_length=10)),
                ('month', models.CharField(db_column='month', default='NULL', max_length=10)),
                ('production', models.CharField(db_column='production', default='NULL', max_length=100)),
                ('actor1', models.CharField(db_column='actor1', default='NULL', max_length=30)),
                ('actor2', models.CharField(db_column='actor2', default='NULL', max_length=30)),
                ('actor3', models.CharField(db_column='actor3', default='NULL', max_length=30)),
                ('imdbVotes', models.IntegerField(db_column='imdbVotes', default=0, max_length=100)),
                ('director', models.CharField(db_column='director', default='NULL', max_length=100)),
                ('genre', models.CharField(db_column='genre', default='NULL', max_length=100)),
                ('rating', models.FloatField(db_column='rating', default=0)),
                ('language', models.CharField(db_column='language', default='NULL', max_length=100)),
                ('country', models.CharField(db_column='country', default='NULL', max_length=50)),
                ('boxoffice', models.FloatField(db_column='boxoffice', default=0)),
                ('runtime', models.IntegerField(db_column='runtime', default=0, max_length=10)),
            ],
        ),
    ]
