# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='directors_by_gross',
            fields=[
                ('rank', models.IntegerField(db_column='rank', primary_key=True, serialize=False)),
                ('director', models.CharField(db_column='director', default='NULL', max_length=100)),
                ('gross_box_office', models.FloatField(db_column='gross_box_office', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='directors_by_rating',
            fields=[
                ('rank', models.IntegerField(db_column='rank', primary_key=True, serialize=False)),
                ('director', models.CharField(db_column='director', default='NULL', max_length=100)),
                ('ave_rating', models.FloatField(db_column='rating', default=0)),
            ],
        ),
    ]
