# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_directors_by_rating_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.IntegerField(db_column='id', default='None', primary_key=True, serialize=False)),
                ('language', models.CharField(db_column='language', default='NULL', max_length=100)),
                ('rating', models.FloatField(db_column='rating', default=0)),
                ('gross_box_office', models.IntegerField(db_column='gross_box_office', default=0)),
                ('number', models.IntegerField(db_column='number', default=0)),
            ],
        ),
    ]
