# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.IntegerField(db_column='id', default='None', primary_key=True, serialize=False)),
                ('country', models.CharField(db_column='country', default='NULL', max_length=100)),
                ('rating', models.FloatField(db_column='rating', default=0)),
                ('gross_box_office', models.FloatField(db_column='gross_box_office', default=0)),
                ('number', models.IntegerField(db_column='number', default=0)),
            ],
        ),
    ]
