# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='month_ave_gross',
            fields=[
                ('id', models.IntegerField(db_column='id', default='None', primary_key=True, serialize=False)),
                ('month', models.CharField(db_column='month', default='NULL', max_length=20)),
                ('ave_gross', models.IntegerField(db_column='gross_box_office', default=0)),
                ('number', models.IntegerField(db_column='number', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='month_list',
            fields=[
                ('id', models.IntegerField(db_column='id', default='None', primary_key=True, serialize=False)),
                ('month', models.CharField(db_column='month', default='NULL', max_length=20)),
                ('rating', models.FloatField(db_column='rating', default=0)),
                ('gross_box_office', models.IntegerField(db_column='gross_box_office', default=0)),
                ('number', models.IntegerField(db_column='number', default=0)),
            ],
        ),
    ]
