# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_month_ave_gross_month_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='month_ave_gross',
        ),
        migrations.AddField(
            model_name='month_list',
            name='ave_gross',
            field=models.IntegerField(db_column='ave_gross', default=0),
        ),
    ]
