# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20171225_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.IntegerField(db_column='id', default='None', primary_key=True, serialize=False)),
                ('production', models.CharField(db_column='production', default='NULL', max_length=100)),
                ('ave_gross', models.IntegerField(db_column='ave_gross', default=0)),
                ('ave_rating', models.FloatField(db_column='rating', default=0)),
                ('gross_box_office', models.IntegerField(db_column='gross_box_office', default=0)),
                ('number', models.IntegerField(db_column='number', default=0)),
            ],
        ),
    ]
