# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='ave_rating',
            field=models.FloatField(db_column='ave_rating', default=0),
        ),
    ]
