# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_actor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='actor',
            new_name='actor_by_gross',
        ),
    ]
