# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_actor_by_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='directors_by_rating',
            name='gross_box_office',
            field=models.FloatField(db_column='gross_box_office', default=0),
        ),
    ]
