# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_directors_by_rating_gross_box_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='year_list',
            fields=[
                ('year', models.IntegerField(db_column='year', default=0, max_length=10, primary_key=True, serialize=False)),
                ('gross_box_office', models.IntegerField(db_column='gross_box_office', default=0)),
                ('number', models.IntegerField(db_column='number', default=0)),
                ('ave_gross', models.IntegerField(db_column='ave_gross', default=0)),
                ('ave_rating', models.FloatField(db_column='ave_rating', default=0)),
            ],
        ),
    ]
