# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_year_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='actor2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(db_column='actor', default='NULL', max_length=100)),
                ('ave_rating', models.FloatField(db_column='ave_rating', default=0)),
                ('gross_box_office', models.FloatField(db_column='gross_box_office', default=0)),
                ('number', models.IntegerField(db_column='number', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='actor3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(db_column='actor', default='NULL', max_length=100)),
                ('ave_rating', models.FloatField(db_column='ave_rating', default=0)),
                ('gross_box_office', models.FloatField(db_column='gross_box_office', default=0)),
                ('number', models.IntegerField(db_column='number', default=0)),
            ],
        ),
    ]
