# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_auto_20180306_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor2',
            name='ave_gross',
            field=models.FloatField(db_column='ave_gross', default=0),
        ),
        migrations.AddField(
            model_name='actor3',
            name='ave_gross',
            field=models.FloatField(db_column='ave_gross', default=0),
        ),
    ]
