# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_auto_20180306_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor2',
            name='actor',
            field=models.CharField(db_column='actor', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actor3',
            name='actor',
            field=models.CharField(db_column='actor', max_length=100, primary_key=True, serialize=False),
        ),
    ]
